// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import "package:flutter/foundation.dart"
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        "DefaultFirebaseOptions have not been configured for web - "
        "you can reconfigure this by running the FlutterFire CLI again.",
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for macos - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for windows - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for linux - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      default:
        throw UnsupportedError(
          "DefaultFirebaseOptions are not supported for this platform.",
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyAuEbUe8_9Fc8XSrTHifkxdVF3h5zK2v_g",
    appId: "1:460590190442:android:ee05cd8e3b8e74c9c89f13",
    messagingSenderId: "460590190442",
    projectId: "take-orders-app-db4b9",
    storageBucket: "take-orders-app-db4b9.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyDmS5L0B5xOiH0A_VTlraN1jZxJxObH0EM",
    appId: "1:460590190442:ios:ce5b3830100f5c9ec89f13",
    messagingSenderId: "460590190442",
    projectId: "take-orders-app-db4b9",
    storageBucket: "take-orders-app-db4b9.appspot.com",
    androidClientId: "460590190442-jbg78ouneotnvqta3heibki2vvtujvb4.apps.googleusercontent.com",
    iosClientId: "460590190442-1civ7jfg6qt5ob7715elsorp6rq7iu4n.apps.googleusercontent.com",
    iosBundleId: "com.arafipro.takeOrdersApp",
  );
}
